### ISSUE TITLE
belgie action tekst huurverzoek

### ISSUE THREAD

**Issue by MyWheels1** [MyWheels/openwheels-frontend#12]
8A	“Je hebt een nieuw huurverzoek van jens voor bolide, wil je het verzoek beantwoorden?” => “Je hebt een nieuw ##reservatie verzoek#### van jens voor bolide, wil je het verzoek beantwoorden?”
8B	knop: “huurverzoek beantwoo

Is het mogelijk voor belgie een andere action met andere tekst te maken?

**Comment by JeffreyAutopia** [comment]
graag vlug in orde brengen. thanx!

![image](https://cloud.githubusercontent.com/assets/12175487/8717137/a5473880-2b98-11e5-8b8e-91f37fa09452.png)

**Comment by barthuttinga** [comment]
Hoi @JeffreyAutopia, het is aangepast. Dwz niet met terugwerkende kracht voor huidige meldingen, maar wel voor nieuwe meldingen die zullen gaan verschijnen.

**Comment by barthuttinga** [comment]
@JeffreyAutopia, toch ook maar even met terugwerkende kracht toegepast, wel zo netjes. Als het goed is staat nu overal "reservatie verzoek" ipv "huurverzoek".

**Comment by JeffreyAutopia** [comment]
hey bart

thanx foor de snelle actie!!

Op 16 juli 2015 09:25 schreef Bart Huttinga <notifications@github.com>:

> @JeffreyAutopia <https://github.com/JeffreyAutopia>, toch ook maar even
> met terugwerkende kracht toegepast, wel zo netjes. Als het goed is staat nu
> overal "reservatie verzoek" ipv "huurverzoek".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MyWheels/openwheels-frontend/issues/12#issuecomment-121857872>
> .
>



-- 

Met vriendelijke groeten,

Jeffrey Matthijs
Coördinator Autopia vzw

*Bekijk hier de foto’s van het Autodeelsalon 2014!
<https://www.facebook.com/media/set/?set=a.10152658609220490.1073741837.66141525489&type=3>*

vind ons leuk op facebook! <https://www.facebook.com/autopia.vzw>


------------------------------------------------------------------
Autopia vzw
Vlaams Netwerk Autodelen
Maria Hendrikaplein 65B
9000 Gent

Telefoon: 09 242 32 75
Website: www.autodelen.net
