### ISSUE TITLE
BELGIE bij mijn gegevens  

### ISSUE THREAD

**Issue by MyWheels1** [MyWheels/openwheels-frontend#19]
huurder en verhuurder veranderen in gebruiker en eigenaar.

en raar : tekst staat onder de box ipv erboven.

**Comment by jorritdenbroeder** [comment]
@MyWheels1, welke box bedoel je, waar de tekst raar onder staat?

**Comment by MyWheels1** [comment]
ik bedoel de kaart instellingen.
in de dropdownbox zelf  staan 2 keuzes, huurder en verhuurder die bedoelt Jeffrey.
Als je het niet ziet assign ticket dan svp aan hem

**Comment by jorritdenbroeder** [comment]
In de Belgische vertaling heb ik "ik gebruik mywheels om te... huren en verhuren" gewijzigd in "ik gebruik mywheels voor... lenen en uitlenen".

**Comment by JeffreyAutopia** [comment]
prima, bedankt!
