### ISSUE TITLE
Autopia, group invoice per maand per auto

### ISSUE THREAD

**Issue by MyWheels1** [MyWheels/openwheels-frontend#2]
Voor autopia
- pas group invoice maken eens per maand (1e van maand s ochtends) of dmv een knop zelf laten kiezen wanneer ze groeperen, vergelijkbaar met huidige pay-knop

**Comment by barthuttinga** [comment]
API call `invoice2.createInvoiceGroup` toegevoegd, met `person` als verplicht argument. Om deze te kunnen uitvoeren zijn de rechten nodig om de invoices van de betreffende persoon te mogen zien.

**Comment by barthuttinga** [comment]
En console command `openwheels:invoice-group:generate` toegevoegd om via cron maandelijks aan te roepen.
