### ISSUE TITLE
Belgie: ritoverzicht pdf

### ISSUE THREAD

**Issue by MyWheels1** [MyWheels/openwheels-frontend#20]
Met goede autopia logo en de mywheels tekst weg

(nu staat er nog mywheels logo boven)
loopt deze niet mee in de branding?

**Comment by JeffreyAutopia** [comment]
als nu klik op het overzicht, krijg ik volgende boodschap: {"error":"invalid_grant","error_description":"The access token provided is invalid."}

**Comment by Aronv90** [comment]
De PDF's worden server side gegenereerd, het MyWheels logo en de tekst onderaan staan hard coded in het bestand print.html.twig. Snelle oplossing is {{ if providerId == 50 }} en dan Autopia logo selecteren. Dat doen?

**Comment by JeffreyAutopia** [comment]
Beste Aron
dat kan maar ik weet eigenlijk niet wat het resultaat is en wat je precies bedoelt :)

**Comment by barthuttinga** [comment]
@Aronv90 en @JeffreyAutopia, we kunnen (delen van) de PDF gewoon overschrijven met specifieke zaken voor Autopia. In ticket #55 zijn logo en teksten voor de verzamelfactuur al opgelost. Volgens mij kan dit ticket dus dicht.
