### ISSUE TITLE
Belgie: op bookingpagina de kosten berekening weg

### ISSUE THREAD

**Issue by MyWheels1** [MyWheels/openwheels-frontend#23]
Dus de hele kosten calculator hiden voor branding belgie

**Comment by JeffreyAutopia** [comment]
dit is nog niet opgelost

**Comment by jorritdenbroeder** [comment]
Waarschijnlijk een misverstand, ik dacht dat we het over deze box hadden:
![capture](https://cloud.githubusercontent.com/assets/6376280/7606377/975767b2-f958-11e4-8cb8-ae84dd135dbd.PNG)

Bedoelde je dan misschien het betalingenoverzicht ("kosten" en "opbrengsten"), dat ook op de boekingpagina staat?

**Comment by JeffreyAutopia** [comment]
Beste Jorrit

Mijn excuses, dat ik nu pas antwoord.  Het gaat over onderstaand geval. bij
reserveer een auto staat het bovenaan goed maar als ik een wagen reserveer
komt er onder de reservatie "kosten". Het is dit dat weg mag.

Is dat duidelijk?

[image: Inline afbeelding 1]

Op 13 mei 2015 10:15 schreef Jorrit den Broeder <notifications@github.com>:

> Waarschijnlijk een misverstand, ik dacht dat we het over deze box hadden:
> [image: capture]
> <https://cloud.githubusercontent.com/assets/6376280/7606377/975767b2-f958-11e4-8cb8-ae84dd135dbd.PNG>
>
> Bedoelde je dan misschien het betalingenoverzicht ("kosten" en
> "opbrengsten"), dat ook op de boekingpagina staat?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MyWheels/openwheels-frontend/issues/23#issuecomment-101566061>
> .
>



-- 

Met vriendelijke groeten,

Jeffrey Matthijs
Coördinator Autopia vzw

*Bekijk hier de foto’s van het Autodeelsalon 2014!
<https://www.facebook.com/media/set/?set=a.10152658609220490.1073741837.66141525489&type=3>*

vind ons leuk op facebook! <https://www.facebook.com/autopia.vzw>


------------------------------------------------------------------
Autopia vzw
Vlaams Steunpunt voor particulier Autodelen
Maria Hendrikaplein 65B
9000 Gent

Telefoon: 09 242 32 75
Website: www.autodelen.net

**Comment by JeffreyAutopia** [comment]
![image](https://cloud.githubusercontent.com/assets/12175487/8717106/2d709a2c-2b98-11e5-9387-2fe7b0e1ad5a.png)

beste dit is nog steeds niet opgelost. er moet enkel aangeduid worden dat de wagen becshikbaar  is zonder daaronder kosten te hebben..
