### ISSUE TITLE
Belgisch adres levert geen goede lat, lon op (ook niet na adres wijzigen)

### ISSUE THREAD

**Issue by MyWheels1** [MyWheels/openwheels-frontend#26]
Werkt het lat lon opvragen via pp6 goed?

**Comment by jorritdenbroeder** [comment]
Deze staat even "on hold" totdat pro6pp ook Belgische adressen voor ons kan opzoeken (abonnement upgrade)

**Comment by JeffreyAutopia** [comment]
kan dit gechekt worden?
