### ISSUE TITLE
oplossing om meer auto's te zoeken dan gepresenteerd worden (K7) 

### ISSUE THREAD

**Issue by MyWheels1** [MyWheels/openwheels-frontend#29]
oplossing met page of infinite scroll

Onderaan lijst een 
"vind meer auto's door in het filter de afstand te vergroten"

**Comment by ANWB1** [comment]
Hallo, 

Dit is toch om eventueel naar een volgende pagina te gaan om de overige auto's in bv Den Haag te zien?
