### ISSUE TITLE
Minimumleeftijd bestuurder AADB24

### ISSUE THREAD

**Issue by MyWheels1** [MyWheels/openwheels-frontend#33]
Er is een minimum leeftijd voor een bestuurder ingevuld. Maar het systeem controleert hier niet op. Het zou huurders onder de leeftijdsgrens geen reservering moeten laten maken.

API moet reservering weigeren met een melding over "Je voldoet niet aan de leeftijds eis voor dit vervoermiddel"

**Comment by MyWheels2** [comment]
Opgelost kan gereleasd als jullie het willen (22 juni meenemen)?

**Comment by ANWB1** [comment]
Hoi,

Prima, neem maar mee 22-6-2015 ☺

Groetjes,
Songul

Van: MyWheels2 [mailto:notifications@github.com]
Verzonden: woensdag 17 juni 2015 14:41
Aan: MyWheels/openwheels-frontend
Onderwerp: Re: [openwheels-frontend] Minimumleeftijd bestuurder AADB24 (#33)


Opgelost kan gereleasd als jullie het willen (22 juni meenemen)?

—
Reply to this email directly or view it on GitHub<https://github.com/MyWheels/openwheels-frontend/issues/33#issuecomment-112783406>.

________________________________

Disclaimer

E-mail wordt door ANWB niet gebruikt voor het aangaan van externe verplichtingen.

Deze e-mail is uitsluitend bestemd voor geadresseerde(n). Indien deze e-mail onverhoopt niet voor u is bestemd dan verzoeken wij u vriendelijk contact op te nemen met de afzender en daarna het bericht te vernietigen. Deze e-mail mag niet worden doorgestuurd, openbaar gemaakt of verveelvoudigd worden zonder de toestemming van de afzender.

ANWB betracht grote zorgvuldigheid bij het verzenden van e-mails. ANWB kan echter niet garanderen dat deze e-mail juist, volledig, tijdig en virusvrij wordt overgebracht. In een dergelijk geval is ANWB op geen enkele wijze aansprakelijk voor enige schade, direct dan wel indirect, in welke vorm dan ook.

ANWB B.V.

________________________________
