### ISSUE TITLE
ver)huurder inlichten over ingevulde kilometers = mailtekst

### ISSUE THREAD

**Issue by MyWheels1** [MyWheels/openwheels-frontend#34]
De verhuurder krijgt geen bericht van de ingevulde kilometers door huurder. 

Als de huurder 0 km invult dan is de rit gesloten en krijgt de verhuurder geen bericht. Is wel een risico, zeker als er meer dan 100km is gereden. De verhuurder zou op de hoogte gesteld moeten worden als de huurder de km stand invult.

? Treedt dit alleen op als 0 ingevuld wordt?

**Comment by ANWB1** [comment]
Ja, want als er meer km's gereden is dan krijgen ze een mail dat ze de extra km's moeten betalen.

**Comment by Aronv90** [comment]
Bram, de huurder krijgt wel een mail, maar de verhuurder niet. Graag de verhuurder per mail informeren als de huurder de km's heeft ingevuld. Zodat hij kan controleren of de huurder dit juist heeft ingevuld.

Wil jij een mail aanmaken die altijd naar de verhuurder wordt verstuurd naar het invullen van de kilometerstanden door de huurder? Hij mag aan voor zowel de ANWB als voor MyWheels. Ticket daarna graag naar mij zodat ik de mailtekst kan schrijven.

**Comment by bramtervoort** [comment]
@lmdehaas Jij wou de tekst wel doen toch? het gaat om http://vespa.site4u.nl:7990/projects/MW/repos/api/browse/src/OpenWheels/ApiBundle/Resources/views/Bookings/tripdata.email.twig?at=refs%2Fheads%2Ffeature%2Fgithub%2334-km-ingevuld-mail

**Comment by ANWB1** [comment]
Hallo Bram,

Is de tekst voor deze mail al gemaakt of zullen wij de tekst aanleveren? Want de verhuurder krijgt nu wel al een mail (in test), maar de zin die in de mail staat is erg sumier. 

Groetjes,
Songul

**Comment by ANWB1** [comment]
De inhoud van de mail klopt niet. Het begin hoort bij ANWB Auto delen, het eind is van Mywheels. Graag de hele inhoud van de mail afstemmen op ANWB Auto delen. 
Zie bijlage. 
![mail afsluiten huurperiode](https://cloud.githubusercontent.com/assets/11739459/9762100/5faf4bb6-5701-11e5-80e6-4f05a3404e8e.jpg)
