### ISSUE TITLE
Footer in mail via Outlook en Gmail niet goed

### ISSUE THREAD

**Issue by ANWB1** [MyWheels/openwheels-frontend#36]
In de ANWB mails zit een footer met "veel gestelde vragen" waar je op kan klikken en dat je dan gelijk naar de pagina gaat waar veel gestelde vragen staat. Als je een mailtje in Outlook of Gmail krijgt, werkt de link niet. Je kan hier niet op klikken. Terwijl de mail via Yahoo wel goed werkt. Kan de mailtjes niet als bijlage bijvoegen, zal ze naar support@mywheels.nl sturen.

**Comment by Aronv90** [comment]
Het probleem is opgelost op bèta, er stond een dubbele link vermelding in de html code. De fix komt bij de volgende release op anwbautodelen.nl te staan.

**Comment by ANWB1** [comment]
In productie getest en de linkjes werken. Ziet er niet echt mooi uit, maar het werkt.
