### ISSUE TITLE
Groeperen sent invoices op dagelijkse basis

### ISSUE THREAD

**Issue by RonaldHav** [MyWheels/openwheels-frontend#38]
conform e-mail wisselling

Graag dagelijks SENT invoices van provider ANWB grouperen en wel ruim voor 05:00 uur want dan halen ze data dupmp op. Dus om 03:00 dagelijks

**Comment by Aronv90** [comment]
Lid 517969 heeft nog een hele rij met Ungrouped sent invoices. Deze zijn niet gegroepeerd. Graag controleren waarom niet.

**Comment by barthuttinga** [comment]
Is gefixt. Zie ook ticket MW-1512 in Jira.

**Comment by ANWB1** [comment]
Hallo Bart,

Wanneer wordt deze in productie gezet?

Groetjes,
Songul

Van: Bart Huttinga [mailto:notifications@github.com]
Verzonden: dinsdag 7 juli 2015 8:36
Aan: MyWheels/openwheels-frontend
Onderwerp: Re: [openwheels-frontend] Groeperen sent invoices op dagelijkse basis (#38)


Is gefixt. Zie ook ticket MW-1512 in Jira.

—
Reply to this email directly or view it on GitHub<https://github.com/MyWheels/openwheels-frontend/issues/38#issuecomment-119089114>.

________________________________

Disclaimer

E-mail wordt door ANWB niet gebruikt voor het aangaan van externe verplichtingen.

Deze e-mail is uitsluitend bestemd voor geadresseerde(n). Indien deze e-mail onverhoopt niet voor u is bestemd dan verzoeken wij u vriendelijk contact op te nemen met de afzender en daarna het bericht te vernietigen. Deze e-mail mag niet worden doorgestuurd, openbaar gemaakt of verveelvoudigd worden zonder de toestemming van de afzender.

ANWB betracht grote zorgvuldigheid bij het verzenden van e-mails. ANWB kan echter niet garanderen dat deze e-mail juist, volledig, tijdig en virusvrij wordt overgebracht. In een dergelijk geval is ANWB op geen enkele wijze aansprakelijk voor enige schade, direct dan wel indirect, in welke vorm dan ook.

ANWB B.V.

________________________________

**Comment by barthuttinga** [comment]
@ANWB1 Hoi Songul, deze fix staat al live (omdat het een taak is die buiten de ANWB-omgeving draait). Afgelopen nacht zijn de verzonden invoices gegroepeerd. Dat gebeurt vanaf nu iedere nacht (rond 3 uur).
