### ISSUE TITLE
knop betalen op dashboard in test werkt niet

### ISSUE THREAD

**Issue by ANWB1** [MyWheels/openwheels-frontend#42]
In de testomgeving werkt de knop ‘Betalen’ op het dashboard niet. Er gebeurt niks. 

Ik heb een reservering gemaakt. Deze is goed gekeurd. Op mijn dashboard verschijnt nu "betalen". Als ik hierop klik gebeurt er niets.

**Comment by jorritdenbroeder** [comment]
Er wordt op dit moment gewerkt aan de financiële module, waardoor dit in de testomgeving inderdaad niet correct werkt. Ik zal het hier posten zodra hij het weer doet, misschien wil je daarna nogmaals testen.

**Comment by jorritdenbroeder** [comment]
@ANWB1 Ik heb begrepen dat hij het weer zou moeten doen. Wil je nog eens testen?

**Comment by ANWB1** [comment]
Ik heb een nieuwe reservering gemaakt, deze goed gekeurd. Als ik naar mijn dashboard ga zie ik nu betalen staan, als ik hierop klik gebeurt er vervolgens niets…

Van: Jorrit den Broeder [mailto:notifications@github.com]
Verzonden: dinsdag 2 juni 2015 13:50
Aan: MyWheels/openwheels-frontend
CC: Songul Sahin
Onderwerp: Re: [openwheels-frontend] knop betalen op dashboard in test werkt niet (#42)


@ANWB1<https://github.com/ANWB1> Ik heb begrepen dat hij het weer zou moeten doen. Wil je nog eens testen?

—
Reply to this email directly or view it on GitHub<https://github.com/MyWheels/openwheels-frontend/issues/42#issuecomment-107926447>.

________________________________

Disclaimer

E-mail wordt door ANWB niet gebruikt voor het aangaan van externe verplichtingen.

Deze e-mail is uitsluitend bestemd voor geadresseerde(n). Indien deze e-mail onverhoopt niet voor u is bestemd dan verzoeken wij u vriendelijk contact op te nemen met de afzender en daarna het bericht te vernietigen. Deze e-mail mag niet worden doorgestuurd, openbaar gemaakt of verveelvoudigd worden zonder de toestemming van de afzender.

ANWB betracht grote zorgvuldigheid bij het verzenden van e-mails. ANWB kan echter niet garanderen dat deze e-mail juist, volledig, tijdig en virusvrij wordt overgebracht. In een dergelijk geval is ANWB op geen enkele wijze aansprakelijk voor enige schade, direct dan wel indirect, in welke vorm dan ook.

ANWB B.V.

________________________________

**Comment by jorritdenbroeder** [comment]
Zou je s.v.p. in je browser op refresh willen drukken (terwijl je op het dashboard bent) en dan nog eens op de betaalknop klikken? Dit even om zeker te zijn dat je naar de meest recente testversie kijkt.

**Comment by ANWB1** [comment]
Hoi,

Dat had ik al een paar keer gedaan, helaas zonder succes. Mijn betaal knop op de dashboard was verdwenen, terwijl ik een reservering voor vanmorgen had. Ik heb net een nieuwe reservering gemaakt en de betaalknop doet het nog steeds niet. Weer een paar keer op refresh geklikt, zonder succes.

Groetjes,
Songul

Van: Jorrit den Broeder [mailto:notifications@github.com]
Verzonden: dinsdag 2 juni 2015 21:03
Aan: MyWheels/openwheels-frontend
CC: Songul Sahin
Onderwerp: Re: [openwheels-frontend] knop betalen op dashboard in test werkt niet (#42)


Zou je s.v.p. in je browser op refresh willen drukken (terwijl je op het dashboard bent) en dan nog eens op de betaalknop klikken? Dit even om zeker te zijn dat je naar de meest recente testversie kijkt.

—
Reply to this email directly or view it on GitHub<https://github.com/MyWheels/openwheels-frontend/issues/42#issuecomment-108058093>.

________________________________

Disclaimer

E-mail wordt door ANWB niet gebruikt voor het aangaan van externe verplichtingen.

Deze e-mail is uitsluitend bestemd voor geadresseerde(n). Indien deze e-mail onverhoopt niet voor u is bestemd dan verzoeken wij u vriendelijk contact op te nemen met de afzender en daarna het bericht te vernietigen. Deze e-mail mag niet worden doorgestuurd, openbaar gemaakt of verveelvoudigd worden zonder de toestemming van de afzender.

ANWB betracht grote zorgvuldigheid bij het verzenden van e-mails. ANWB kan echter niet garanderen dat deze e-mail juist, volledig, tijdig en virusvrij wordt overgebracht. In een dergelijk geval is ANWB op geen enkele wijze aansprakelijk voor enige schade, direct dan wel indirect, in welke vorm dan ook.

ANWB B.V.

________________________________

**Comment by jorritdenbroeder** [comment]
@ANWB1 Bedankt voor het controleren. Ik was te voorbarig, de testversie staat nu pas online.  Je kunt het dus normaals proberen, bij mij doet de knop het nu wel. Btw, 1x refreshen is genoeg om de applicatie te verversen.

**Comment by ANWB1** [comment]
Wanneer wordt dit in productie gezet?

Van: Jorrit den Broeder [mailto:notifications@github.com]
Verzonden: woensdag 3 juni 2015 12:40
Aan: MyWheels/openwheels-frontend
CC: Songul Sahin
Onderwerp: Re: [openwheels-frontend] knop betalen op dashboard in test werkt niet (#42)


Closed #42<https://github.com/MyWheels/openwheels-frontend/issues/42>.

—
Reply to this email directly or view it on GitHub<https://github.com/MyWheels/openwheels-frontend/issues/42#event-321014212>.

________________________________

Disclaimer

E-mail wordt door ANWB niet gebruikt voor het aangaan van externe verplichtingen.

Deze e-mail is uitsluitend bestemd voor geadresseerde(n). Indien deze e-mail onverhoopt niet voor u is bestemd dan verzoeken wij u vriendelijk contact op te nemen met de afzender en daarna het bericht te vernietigen. Deze e-mail mag niet worden doorgestuurd, openbaar gemaakt of verveelvoudigd worden zonder de toestemming van de afzender.

ANWB betracht grote zorgvuldigheid bij het verzenden van e-mails. ANWB kan echter niet garanderen dat deze e-mail juist, volledig, tijdig en virusvrij wordt overgebracht. In een dergelijk geval is ANWB op geen enkele wijze aansprakelijk voor enige schade, direct dan wel indirect, in welke vorm dan ook.

ANWB B.V.

________________________________

**Comment by jorritdenbroeder** [comment]
Het probleem dat je hebt ervaren deed zich alleen voor in de testomgeving. Voor ANWB zijn er geen wijzigingen gepland wat betreft de betalingen, op de productieservers blijft alles dus zoals het was.
