### ISSUE TITLE
Huurovereenkomst op de site zichtbaar voodat de reservering betaald is.

### ISSUE THREAD

**Issue by ANWB1** [MyWheels/openwheels-frontend#43]
Nadat de verhuurder de reservering heeft geaccepteerd, is op de site zowel voor de huurder als de verhuurder de overeenkomst al zichtbaar. Deze zou pas zichtbaar mogen zijn nadat de reservering is betaald. Dan is de reservering definitief.

**Comment by MyWheels2** [comment]
Opgelost kan gereleasd als jullie het willen (22 juni meenemen)?

**Comment by ANWB1** [comment]
Hoi,

Doen.

Groetjes,
Songul

Van: MyWheels2 [mailto:notifications@github.com]
Verzonden: woensdag 17 juni 2015 14:43
Aan: MyWheels/openwheels-frontend
CC: Songul Sahin
Onderwerp: Re: [openwheels-frontend] Huurovereenkomst op de site zichtbaar voodat de reservering betaald is. (#43)


Opgelost kan gereleasd als jullie het willen (22 juni meenemen)?

—
Reply to this email directly or view it on GitHub<https://github.com/MyWheels/openwheels-frontend/issues/43#issuecomment-112784370>.

________________________________

Disclaimer

E-mail wordt door ANWB niet gebruikt voor het aangaan van externe verplichtingen.

Deze e-mail is uitsluitend bestemd voor geadresseerde(n). Indien deze e-mail onverhoopt niet voor u is bestemd dan verzoeken wij u vriendelijk contact op te nemen met de afzender en daarna het bericht te vernietigen. Deze e-mail mag niet worden doorgestuurd, openbaar gemaakt of verveelvoudigd worden zonder de toestemming van de afzender.

ANWB betracht grote zorgvuldigheid bij het verzenden van e-mails. ANWB kan echter niet garanderen dat deze e-mail juist, volledig, tijdig en virusvrij wordt overgebracht. In een dergelijk geval is ANWB op geen enkele wijze aansprakelijk voor enige schade, direct dan wel indirect, in welke vorm dan ook.

ANWB B.V.

________________________________

**Comment by ANWB1** [comment]
Hoi,

Is dit al in de testomgeving geplaatst?
Ik heb namelijk net gecheckt en zie hieronder:
Als Test-D wil ik de auto van Test-C reserveren. Als ik als Test-C op de aanvraag klik, zie ik vervolgens al een huurovereenkomst staan. Hier zou het nog niet zichtbaar moeten zijn. Mag pas na betaling.
Als ik als Test-D op de aanvraag klik, zie ik geen huurovereenkomst. 

Nadat Test-C het verzoek van Test-D heeft geaccepteerd, zie ik als Test-D ook al de huurovereenkomst. Ik heb nog niet betaalt. Zou dus nog niet zichtbaar mogen zijn.

Groetjes,
Songul

**Comment by bramtervoort** [comment]
Volgens mij moet alleen de knop nog verdwijnen in de frondend hij is al niet meer zichtbaar
