### ISSUE TITLE
Betalingen worden niet goed geregistreerd op anwb autodelen

### ISSUE THREAD

**Issue by ANWB1** [MyWheels/openwheels-frontend#44]
Zie mailwisseling met Danielle en Tobias.
Een betaling is wel verricht, alleen wordt dit niet goed weergegeven in het systeem. Hier lijkt het alsof de huurder niet betaald heeft en wordt dus vervolgd door een annulering.

**Comment by barthuttinga** [comment]
Zie mail van Tobias aan support op 11-06-2015 15:50

**Comment by barthuttinga** [comment]
Na update van server trad een probleem op bij verzenden van logs/mails, daardoor ging er ook iets mis met het bijwerken van de status van de betaling. Is al ruime tijd opgelost en heeft zich niet opnieuw voorgedaan, voor zover mij bekend. Ik sluit het ticket.
