### ISSUE TITLE
als huurder huurverzoek doet moet verhuurder adres en zo van huurder kunnen zien

### ISSUE THREAD

**Issue by RonaldHav** [MyWheels/openwheels-frontend#45]
zodat je kan oordelen of je wilt verhuren.

bijvoorbeeld op de profiel pagina en bij de boeking

(het gaat erom dat de API rechten goed staat)

Volledige naam, adres plaats, telefoon, gebdat, email, badges,

**Comment by MyWheels2** [comment]
bijvoorbeeld op de profiel pagina en bij de boeking

(het gaat erom dat de API rechten goed staat)

**Comment by ANWB1** [comment]
We hebben dit vandaag getest, maar er is nog geen adres te zien voor de verhuurder. Wanneer wordt dit uitgerold? (Er staat 'next release - 22 jun)
