### ISSUE TITLE
Finance interface verhuurder vs betalingen

### ISSUE THREAD

**Issue by ANWB1** [MyWheels/openwheels-frontend#46]
Zie mailwisseling van 3 juni en support ID #875803.

**Comment by barthuttinga** [comment]
@ANWB1 Ik sluit dit ticket, want opgelost. Verhuurder ziet de ID´s van de invoices, welke corresponderen met de nummers op het bankafschrift. Kopje "Nog te ontvangen" wordt straks nog even aangepast naar "Verhuuropbrengsten".
