### ISSUE TITLE
verzoek aanpassing exportbestand anwb_resources.csv

### ISSUE THREAD

**Issue by ANWB1** [MyWheels/openwheels-frontend#48]
data uit het bestand anwb_resources.csv uit  breiden met merk en model van de deelauto’s.

(Zie mailwisseling van 3 juni en support ID #886677.)

**Comment by Aronv90** [comment]
Tobias: Ik heb meteen gecheckt of eea bij ons correct binnenkomt en zie nu merk en model in resources. Probleem is wel dat de data niet in de meest rechterkolom staat maar er tussen. Dit kan tot mi issues leiden. Kun je ervoor zorgen dat in het bestand anwb_resources.csv het merk en model in de meest rechterkolom staan?
