### ISSUE TITLE
Information box disappears behind menu-bar (CSS)

### ISSUE THREAD

**Issue by wilfreddijksman** [MyWheels/openwheels-frontend#5]
When you hover over the "I"-icon the information box disappears behind the menu-bar 😞
On a live site: https://mywheels.nl/m/#/resource/7345
![The problem on a live site](https://cloud.githubusercontent.com/assets/1773594/7379789/9892bf8a-edf7-11e4-9c31-be7c5de82d48.png)

**Comment by jorritdenbroeder** [comment]
Thanks, this has been solved already - just not online yet.
