### ISSUE TITLE
ANWB Annuleren binnen 4 uur + nieuwe reservering maken / verrekenen

### ISSUE THREAD

**Issue by MyWheels2** [MyWheels/openwheels-frontend#50]
Omdat de Verhuurder een reservering heeft geannuleerd binnen 4 uur voor aanvang krijgt de huurder geld terug. Maar als deze huurder nu een nieuwe reservering maakt lijkt het erop dat het bedrag van de nieuwe reservering wordt verrekend met het openstaande bedrag. Hierdoor kan de huurder de reservering niet betalen. Als die huurder vervolgens nóch een reservering maakt moet hij de vorige reservering ineens toch betalen. (komt vermoedelijk omdat het terug storten nog niet is gebeurd) Dit lijkt mij geen show stopper want dit zal in de praktijk niet snel gebeuren. Maar er moet wél naar gekeken worden.

bron http://support.mywheels.nl/scp/tickets.php?id=23468

**Comment by barthuttinga** [comment]
@ANWB1 De omschrijving van dit ticket komt uit de mail van Merijn op 08-07-2015 11:29. Ik kan dit probleem niet geproduceren. Verhuurder annuleert betaalde boeking binnen vier uur. Dat resulteert in credit-facturen. Huurder maakt nieuwe boeking, verhuurder accepteert, er onstaan nieuwe facturen. Huurder kan deze afrekenen. Huurder maakt nog een boeking, verhuurder accepteert, er ontstaan weer nieuwe facturen. Huurder kan deze afrekenen. Niks geks tot zover, toch? Of begrijp ik het probleem verkeerd?

**Comment by ANWB1** [comment]
Hallo Bart,

Ik heb het zelf net ook geprobeerd te reproduceren en mij lukte het ook niet. Waarschijnlijk waren we vorige week nog sneller met annuleren en opnieuw een reservering maken.

We hadden inderdaad een reservering gemaakt en betaald. Verhuurder had binnen 4 uur geannuleerd. En direct hadden we weer een reservering gemaakt en deze was geaccepteerd. Dan zag je in je financiën aan het eind te betalen 0 staan. Je kon dus je reservering niet betalen, waardoor deze niet definitief werd.

Maar net zeg ik gewoon het bedrag staan wat ik moest betalen.

Je kan de ticket sluiten en mochten we er later weer een keer tegen aan lopen, kunnen we het alsnog openen.

Groetjes,
Songul

Van: Bart Huttinga [mailto:notifications@github.com]
Verzonden: donderdag 16 juli 2015 11:23
Aan: MyWheels/openwheels-frontend
CC: Songul Sahin
Onderwerp: Re: [openwheels-frontend] ANWB Annuleren binnen 4 uur + nieuwe reservering maken / verrekenen (#50)


@ANWB1<https://github.com/ANWB1> De omschrijving van dit ticket komt uit de mail van Merijn op 08-07-2015 11:29. Ik kan dit probleem niet geproduceren. Verhuurder annuleert betaalde boeking binnen vier uur. Dat resulteert in credit-facturen. Huurder maakt nieuwe boeking, verhuurder accepteert, er onstaan nieuwe facturen. Huurder kan deze afrekenen. Huurder maakt nog een boeking, verhuurder accepteert, er ontstaan weer nieuwe facturen. Huurder kan deze afrekenen. Niks geks tot zover, toch? Of begrijp ik het probleem verkeerd?

—
Reply to this email directly or view it on GitHub<https://github.com/MyWheels/openwheels-frontend/issues/50#issuecomment-121897626>.

________________________________

Disclaimer

E-mail wordt door ANWB niet gebruikt voor het aangaan van externe verplichtingen.

Deze e-mail is uitsluitend bestemd voor geadresseerde(n). Indien deze e-mail onverhoopt niet voor u is bestemd dan verzoeken wij u vriendelijk contact op te nemen met de afzender en daarna het bericht te vernietigen. Deze e-mail mag niet worden doorgestuurd, openbaar gemaakt of verveelvoudigd worden zonder de toestemming van de afzender.

ANWB betracht grote zorgvuldigheid bij het verzenden van e-mails. ANWB kan echter niet garanderen dat deze e-mail juist, volledig, tijdig en virusvrij wordt overgebracht. In een dergelijk geval is ANWB op geen enkele wijze aansprakelijk voor enige schade, direct dan wel indirect, in welke vorm dan ook.

ANWB B.V.

________________________________

**Comment by barthuttinga** [comment]
@ANWB1 prima, dan sluit ik hem nu, mocht het toch weer optreden dan mag je hem heropenen
