### ISSUE TITLE
Telefoonnummer verplicht maken

### ISSUE THREAD

**Issue by ANWB1** [MyWheels/openwheels-frontend#51]
Aron Vaas mailde op 8-7-2015:
Het veld telefoonnummer gaan we verplicht maken. De knop Opslaan maken we nu alleen beschikbaar als er een telefoonnummer ingevuld is. Ik heb een ticket aangemaakt

Ik zag in GitHub geen ticket, dus vandaar een aangemaakt.

**Comment by Aronv90** [comment]
Op de pagina Mijn gegevens (http://anwb-test.openwheels.nl/dashboard/profile) wordt je telefoonnummer gevraagd. Daar staat bij: Verplicht. Toch kun je de gegevens opslaan zonder telefoonnummer in te vullen. Oplossing: de knop Opslaan alleen beschikbaar maken als telefoonnummer ingevuld is.

**Comment by Aronv90** [comment]
https://github.com/MyWheels/openwheels-frontend/pull/63
