### ISSUE TITLE
Als een reservering geannuleerd wordt, zie je nu een zwarte streep, hier zou geannuleerd moeten staan

### ISSUE THREAD

**Issue by ANWB1** [MyWheels/openwheels-frontend#52]
Bij de annulering na betaling staat op het dashboard van de huurder de reservering met een zwarte streep op de plek van de status. Dit zou “Geannuleerd” moeten zijn. 

Antwoord Aron 8-7-2015:
De status owner_cancelled (als de eigenaar een geaccepteerde reservering weer annuleert) was nog niet in de front doorgevoerd. We zullen zorgen dat bij deze status de website ook de tekst Geannuleerd toont. Ik heb een ticket aangemaakt.

**Comment by Aronv90** [comment]
In de front is de status owner_cancelled nog niet doorgevoerd. Graag op plekken waar de boekingsstatus cancelled staat, ook owner_cancelled toevoegen. Label mag gewoon Geannuleerd blijven.
