### ISSUE TITLE
vervangen woorden

### ISSUE THREAD

**Issue by JeffreyAutopia** [MyWheels/openwheels-frontend#53]
![image](https://cloud.githubusercontent.com/assets/12175487/8717250/dc330382-2b99-11e5-8235-ce9d3bb58375.png)
![image](https://cloud.githubusercontent.com/assets/12175487/8717640/9220a98a-2b9d-11e5-8938-588c869c5b84.png)

huurders => gebruikers
verhuurperiodes => gebruikersperiodes

**Comment by Aronv90** [comment]
Aangepast
