### ISSUE TITLE
vervangen woorden 2

### ISSUE THREAD

**Issue by JeffreyAutopia** [MyWheels/openwheels-frontend#54]
![image](https://cloud.githubusercontent.com/assets/12175487/8718409/8187d8b2-2ba4-11e5-9c5a-b29283f35f87.png)

“Mijn verhuuropbrengsten” => “te ontvangen bij volgende afrekening”
“huur” (bij de ritten) => “uren”

knop betalen mag weg

**Comment by Aronv90** [comment]
Misschien beter om de tekst in de taalbestanden te zetten?

**Comment by jorritdenbroeder** [comment]
“Mijn verhuuropbrengsten” => “te ontvangen bij volgende afrekening”
Deze is inmiddels aangepast, s.v.p. even geduld tot de volgende release heeft plaatsgevonden.

“huur” (bij de ritten) => “uren”
Dit is niet eenvoudig. Wat je hier ziet is tekst die wordt gegenereerd door de factuurmodule (de tekst verschijnt ook letterlijk op facturen) en die is op dit punt helaas niet aanpasbaar. Indien je het zeer belangrijk vindt, wil je dan contact opnemen met MyWheels?

**Comment by JeffreyAutopia** [comment]
Beste Jorrit

we laten het voorlopig zo en zien wel wat de testers ervan zeggen.

alvast bedankt voor alle werk!

Op 7 augustus 2015 09:46 schreef Jorrit den Broeder <
notifications@github.com>:

> “Mijn verhuuropbrengsten” => “te ontvangen bij volgende afrekening”
> Deze is inmiddels aangepast, s.v.p. even geduld tot de volgende release
> heeft plaatsgevonden.
>
> “huur” (bij de ritten) => “uren”
> Dit is niet eenvoudig. Wat je hier ziet is tekst die wordt gegenereerd
> door de factuurmodule (de tekst verschijnt ook letterlijk op facturen) en
> die is op dit punt helaas niet aanpasbaar. Indien je het zeer belangrijk
> vindt, wil je dan contact opnemen met MyWheels?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MyWheels/openwheels-frontend/issues/54#issuecomment-128626052>
> .
>



-- 

Met vriendelijke groeten,

Jeffrey Matthijs
Coördinator Autopia vzw

*Bekijk hier de foto’s van het Autodeelsalon 2014!
<https://www.facebook.com/media/set/?set=a.10152658609220490.1073741837.66141525489&type=3>*

vind ons leuk op facebook! <https://www.facebook.com/autopia.vzw>


------------------------------------------------------------------
Autopia vzw
Vlaams Netwerk Autodelen
Maria Hendrikaplein 65B
9000 Gent

Telefoon: 09 242 32 75
Website: www.autodelen.net
