### ISSUE TITLE
verzamelfactuur

### ISSUE THREAD

**Issue by JeffreyAutopia** [MyWheels/openwheels-frontend#55]
![image](https://cloud.githubusercontent.com/assets/12175487/8718509/1dfed038-2ba5-11e5-8da2-37a641ddd1d4.png)

algemene vraag/ is het mogelijk om een verzamelfactuur te ontvangen voor elke auto apart? Is het mogelijk om telkens het rekeningnummer van de eigenaar te vermelden?
kan de knop om de verzamelfactuur te activeren beschikbaar gesteld worden voor de backoffice van Autopia?

andere aanpassingen
logo mywheels vervangen door Autopia
"huur" => "tijdsduur"

vervangen: "MyWheels is een handelsnaam van Wheels4all BV, KvK: 37133089, BTW-nr: NL
8180.30.306 B01 rekeningnr: NL29 RABO 0159.955.734, info@MyWheels.nl, Het Voert
9e, 1613 KL Grootebroek." => "gelieve het openstaande bedrag binnen de twee weken over te maken op het rekeningnummer van de eigenaar"

"MyWheels is het non-profit platform voor het delen van auto's. Het is dé plek waar
mensen, die een auto zoeken en aanbieden, elkaar vinden.
 mywheels.nl  support@mywheels.nl  0228-514824" => " Autopia is het Vlaams Netwerk Autodelen en faciliteert autodelen met je buren. Bovendien prommot ze autodelen in al zijn vormen!
www.autodelen.net  autopia@autodelen.net  09/242.32.75"

**Comment by barthuttinga** [comment]
Hoi @JeffreyAutopia, wat bedtreft je eerste vraag `is het mogelijk om een verzamelfactuur te ontvangen voor elke auto apart?`, daar heb ik even een apart ticket voor gemaakt (#56), ga ik zo naar kijken.

De rest van dit ticket is opgelost en ga ik zo live zetten.

**Comment by JeffreyAutopia** [comment]
Dat is inderdaad ok! bedankt!

ik heb nog eenk kleine vraag
![image](https://cloud.githubusercontent.com/assets/12175487/8825402/1be3a3d0-307f-11e5-973f-c0b17ef157c9.png)

bij de eerste twee staat het rekeningnummer en bij de laatste niet. Ben ik juist als ik zeg dat als de eigenaar een rekeningnummer invoerde, dit dan ook verschijnt bij de desbetreffende rit. indien dat zo is, denk ik, hebben we een goede oplossing!

groetjes

**Comment by barthuttinga** [comment]
@JeffreyAutopia, inderdaad, het rekeningnummer wordt getoond als het bekend is. Is het niet bekend, dan wordt het gewoon leeggelaten (zoals bij onderste rit).
