### ISSUE TITLE
Aparte verzamelfactuur voor elke auto (autopia)

### ISSUE THREAD

**Issue by barthuttinga** [MyWheels/openwheels-frontend#56]
zie #55

**Comment by barthuttinga** [comment]
@JeffreyAutopia, ik heb er even naar gekeken. Binnen de huidige functionaliteit kunnen we groeperen rondom een persoon of een boeking. Dus niet rond een auto. Is dat acceptabel? Het kan natuurlijk wel gemaakt worden als dat nodig is. Graag je reactie.

**Comment by JeffreyAutopia** [comment]
Beste Bart

Rondom een persoon, betekent dit "de persoonlijke" rekening van die
persoon. Dus de ritten die deze persoon heeft uitgevoerd en dus b
verschillende auto's( eigenaars)?
rondom een boeking, kan ik hier wat meer uitleg over krijgen want dat vat
ik niet helemaal.

punt is dat wij werken met gesloten groepen waarin meerdere auto's kunnen
aangesloten zijn.Het handigste is dat we een overzicht hebben van de
totaalprijs mer auto. maar dit is op dit moment niet mogelijk begrijp ik.
Kunnen we de overzichten in excell krijgen zodat we eventueel zelf
bewerkingen kunnen maken?

misschien kunnen we even telefonisch contact hebben om op elkaar af te
stemmen? Ik kan in principe morgen (vanaf rond 12u)  en vrijdag (tussen 10u
en 12u)

groetjes en tot binnenkort

Op 20 juli 2015 11:17 schreef Bart Huttinga <notifications@github.com>:

> @JeffreyAutopia <https://github.com/JeffreyAutopia>, ik heb er even naar
> gekeken. Binnen de huidige functionaliteit kunnen we groeperen rondom een
> persoon of een boeking. Dus niet rond een auto. Is dat acceptabel? Het kan
> natuurlijk wel gemaakt worden als dat nodig is. Graag je reactie.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MyWheels/openwheels-frontend/issues/56#issuecomment-122820665>
> .
>



-- 

Met vriendelijke groeten,

Jeffrey Matthijs
Coördinator Autopia vzw

*Bekijk hier de foto’s van het Autodeelsalon 2014!
<https://www.facebook.com/media/set/?set=a.10152658609220490.1073741837.66141525489&type=3>*

vind ons leuk op facebook! <https://www.facebook.com/autopia.vzw>


------------------------------------------------------------------
Autopia vzw
Vlaams Netwerk Autodelen
Maria Hendrikaplein 65B
9000 Gent

Telefoon: 09 242 32 75
Website: www.autodelen.net
