### ISSUE TITLE
kan de knop om de verzamelfactuur te activeren beschikbaar gesteld worden voor de backoffice van Autopia?

### ISSUE THREAD

**Issue by barthuttinga** [MyWheels/openwheels-frontend#57]
Hoi @JeffreyAutopia, deze vraag van jou komt uit ticket #55, maar ik snap niet helemaal wat je ermee bedoelt. Kan je het toelichten?

**Comment by JeffreyAutopia** [comment]
Dag Bart

Ronald vertelde me dat er maandelijks fysiek een opdracht tot maken van verzamelfacturen kon geprogrammeerd worden. Deze opdracht zou dan ofwel automatisch gaan, ofwel zouden wij vanuit Autopia maandelijks op een knop moeten duwen die de opdracht activeert

Deze zou dan bij voorkeur in de backoffice zitten (zie link)
https://openwheels.nl/backoffice/index.html#/person/507799

is dit iets duidelijker?
