### ISSUE TITLE
Datum en time picker

### ISSUE THREAD

**Issue by mat1th** [MyWheels/openwheels-frontend#605]
De date en time picker die op dit moment gebruikt word, is niet gemakkelijk in gebruikt, zeker op mobiele apparaten. Het is een oplossing hiervoor is om bijvoorbeeld deze data picker te gebruiken: > https://chmln.github.io/flatpickr/examples/ Deze valt terug op de native date picker op iOS en Android en op desktop werkt hij ook gemakkelijk.

**Comment by j-mywheels** [comment]
Ik vind de time picker wat onhandig werken, maar voor de rest ziet het er wel goed uit. @mat1th

**Comment by mat1th** [comment]
@j-mywheels Het klopt dat er betere interacties zijn, maar voor angular.js heb ik geen andere kunnen vinden die zo goed werkt op verschillende aparaten. 
Eenje die een betere interactie heeft, maar niet met angular werkt is deze > https://github.com/airbnb/react-dates.
