### ISSUE TITLE
Mouse-over "i" bij 100km gratis icoon geeft verkeerde tekst. 

### ISSUE THREAD

**Issue by ANWB1** [MyWheels/openwheels-frontend#68]
Wanneer je met de muis over het icoon "i" gaat verschijnt er een tekst "of 10km per uur gratis als je onder de dagprijs blijft". Deze tekst moet veranderd worden. Ik zal na vragen welke tekst er wel moet staan. (als er überhaupt een tekst moet staan. 

![100km-ietje](https://cloud.githubusercontent.com/assets/11739459/9193293/7e62ab44-4012-11e5-98ea-87f8c44966d9.jpg)

**Comment by ANWB1** [comment]
De tekst die bij het icoon hoort te staan moet zijn: 
"Voor deze auto geldt dat je pas kilometers gaat betalen als je meer dan 100 km hebt gereden"
Als deze tekst te lang is dan: 
"100 kilometer gratis"

**Comment by jorritdenbroeder** [comment]
Ik heb voor de lange tekst gekozen, dus "Voor deze auto geldt dat je pas kilometers gaat betalen als je meer dan 100 km hebt gereden".

**Comment by Aronv90** [comment]
ANWB belde: De tekstballon van het i'tje valt nu onder de menubalk weg. Kun je ervoor zorgen dat de tekstballon onder het i'tje wordt getoond?

![2015-08-20 16_08_02-greenshot](https://cloud.githubusercontent.com/assets/11392533/9385260/b0c59804-4755-11e5-9511-83849220ad58.png)

**Comment by jorritdenbroeder** [comment]
Klopt, dit had ik over het hoofd gezien maar is nu opgelost. Het gebeurde alleen als je scherm tussen 992-1200 pixels breed is.

**Comment by ANWB1** [comment]
Ik heb dit in de testomgeving bekeken, maar daar staat de popup nog steeds boven de muis, en dus achter de menubalk. De resolutie van mijn scherm is 1680x1050, maar dat zou volgens mij niet uit moeten maken voor de locatie van de popup. Of zie ik dat verkeerd?

**Comment by jorritdenbroeder** [comment]
Excuus, de testomgeving is overgeslagen - het is direct naar productie gegaan.

Om precies te zijn heeft het met een combinatie van vensterbreedte en zoomfactor te maken. Bijv. Google Chrome, bij een zoomfactor van 125% en > 1200px is de tooltip wel volledig zichtbaar.
