### ISSUE TITLE
Meta tags toevoegen aan lid pagina's

### ISSUE THREAD

**Issue by Aronv90** [MyWheels/openwheels-frontend#70]
Graag ook title en description tags toevoegen de lid pagina (https://mywheels.nl/lid/316909). Graag voor huurders en verhuurders verschillende tags:

Huurders (renters)
Title: {Aron} huurt deelauto's via MyWheels | MyWheels 
Description: {Aron} huurt deelauto's in {Blokker} via MyWheels

Verhuurders (owners en both)
Title: {Aron} verhuurt een auto in {Blokker} | MyWheels
Description: {Aron} deelt een auto {Opel Astra} via MyWheels in {Blokker}

**Comment by jorritdenbroeder** [comment]
Voor niet-ingelogde gebruikers (en dus ook Google Bot) geeft de api-call slechts minimale informatie: alleen voornaam en aantal x gehuurd. Om de tags die je voorstelt te genereren is meer info nodig namelijk preference (owner/renter/both) en stad. Aron, maak jij een issue aan voor de API? person.get({ version: 2, person: <id> })

In het geval van verhuurders doen we overigens al een aparte request voor de auto's. Aan de hand daarvan kunnen we de autonaam invullen.

**Comment by jorritdenbroeder** [comment]
@Aronv90 wat is de status?

**Comment by Aronv90** [comment]
Bram heeft ticket MW-1877 verwerkt, in de API call worden nu preference en city meegegeven.
