### ISSUE TITLE
Meta tags niet overgenomen door Google

### ISSUE THREAD

**Issue by Aronv90** [MyWheels/openwheels-frontend#72]
De meta tags worden volgens mij nog niet goed overgenomen door Google. Zie screenshot bij de volgende zoekopdracht: https://www.google.nl/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=13775%20site%3Amywheels.nl
![2015-08-28 17_04_32-greenshot](https://cloud.githubusercontent.com/assets/11392533/9549544/e132d3a6-4da6-11e5-8d81-815e2b5a2092.png)

**Comment by jorritdenbroeder** [comment]
Hotfixed in 2bc2beb3703b3a31a860a8398373c0465194518e
