### ISSUE TITLE
Toon kleur ANWB Lidmaatschap

### ISSUE THREAD

**Issue by ANWB1** [MyWheels/openwheels-frontend#73]
We willen graag de kleur van het ANWB Lidmaatschap tonen op de website van ANWB Autodelen. 
Nu wordt alleen getoond of iemand lid is van de ANWB, maar we willen graag de kleur van het lidmaatschap tonen. De loyaliteits-checker geeft deze informatie al door. Het moet nog wel in applicatie geprogrammeerd worden. Dit is reeds met Ronald Haverman besproken, hij zal opgeven hoeveel uren hiervoor nodig zijn. Wij moeten icoontjes in verschillende kleuren aanleveren, of de kleurcodes zodat het icoon aangepast kan worden. 
Het idee is dat er vijf verschillende kleuren iconen zijn die de kleur van het lidmaatschap weergeven. Er komt dan een informatie-icoon (i) bij met een popup waarin een uitleg staat wat elke kleur betekent. (blauw tot vijf jaar lid, brons tussen 5 en tien...  etc)

**Comment by barthuttinga** [comment]
API:
- imageUrl toevoegen aan BadgeType
- category toevoegen aan BadgeType
- BadgeType per kleur aanmaken
- onderhoudstaak maken die controleert op nieuwe kleur en zonodig oude badges (in ANWB category) weggooit

Front:
- image van Badge weergeven indien aanwezig, anders standaard (zoals nu)

**Comment by ANWB1** [comment]
Het kost wat meer tijd dan verwacht om de juiste kleurcode en/of iconen te achterhalen. De ANWB blijkt toch weer erg groot :) 
Daarnaast zullen we in het volgende beheer overleg bespreken wanneer we dit willen doorvoeren. Nog even geduld dus.

**Comment by ANWB1** [comment]
Voorlopig voeren we geen vernieuwingen door op de pilotomgeving. Daarom wordt deze melding gesloten.
