### ISSUE TITLE
Fixtures voor testomgeving. 

### ISSUE THREAD

**Issue by ANWB1** [MyWheels/openwheels-frontend#79]
Zie mail van Ronald van 30 april 2015. 

Van: MyWheels | Ronald Haverman [mailto:ronald@mywheels.nl] 
Verzonden: donderdag 30 april 2015 15:11
Aan: Songul Sahin
CC: Merijn van Beinum
Onderwerp: Re: testomgeving

De testomgeving wordt steeds automatisch leeggegooid en werkt met fixtures. Dat is een kleine set gegevens die er steeds ingeladen wordt na legen. Dat is wat lastig, maar je kunt gewoon weer leden toevoegen. Ook kun je eventueel fixtures aanleveren die wij standaard weer moeten inladen.

Graag de fixtures in de bijlage toevoegen voor alle komende releases. 

![fixtures](https://cloud.githubusercontent.com/assets/11739459/9761209/93243fd4-56fb-11e5-97b9-9b9214b8e13f.JPG)

**Comment by barthuttinga** [comment]
Fixtures zijn toegevoegd.

**Comment by ANWB1** [comment]
Hallo Bart, 
Wil je alsjeblieft nog één keer naar de fixtures kijken. We merkten dat het niet handig is om geen adressen in te vullen, en ook het lidmaatschap en het IBAN nummer hebben we toegevoegd. 
Ook had niet iedereen een rijbewijs gekoppeld.Heb je hier een plaatje van nodig? Laat het ons dan even weten alsjeblieft. 

![fixtures anwb autodelen](https://cloud.githubusercontent.com/assets/11739459/10046979/1a07a426-620c-11e5-8336-baa7b41e5ab2.jpg)

Als laatste hebben we nog één vraag. Volgens mij was het zo dat je, als je hebt aangegeven geen lidmaatschapsnummer van de ANWB in te vullen (kruisje bij de actie op je dashboard) dan kon je later toch nog ergens je lidmaatschapsnummer toevoegen. Voor als je je bedenkt. Maar weet jij de link hiervoor? 

Groetjes,
Merijn en Songul

**Comment by barthuttinga** [comment]
Hoi Merijn en Songul, de adressen, autolocaties, IBANs en lidmaatschapnummers zijn toegevoegd. Ook heb ik de huurders (C, D en F) een contract gegeven, zodat ze kunnen huren. Maakt dat de rijbewijzen overbodig? Of moeten die er alsnog bij?

De link voor ANWB-nummer is https://www.anwbautodelen.nl/dashboard/anwb-id

Groeten Bart
