### ISSUE TITLE
belgie taalbestand: 

### ISSUE THREAD

**Issue by MyWheels1** [MyWheels/openwheels-frontend#8]
: “Belgie_verhuurder” => België_eigenaar, #niet aangetroffen

“Hoeveelheid e-mails van MyWheels” => “Hoeveel e-mails wil je ontvangen ” deze basis tabel!!

8A	“Je hebt een nieuw huurverzoek van jens voor bolide, wil je het verzoek beantwoorden?” => “Je hebt een nieuw ##reservatie verzoek#### van jens voor bolide, wil je het verzoek beantwoorden?”
8B	knop: “huurverzoek beantwoo, = action, ander ticket

“opmerking voor de huurder” => “opmerking voor de gebruiker”
jeffrey wil jouw auto huren => “jeffrey wil jouw auto gebruiken”

**Comment by JeffreyAutopia** [comment]
“Belgie_verhuurder” => België_eigenaar, #ok

**Comment by JeffreyAutopia** [comment]
“Hoeveelheid e-mails van MyWheels” => “Hoeveel e-mails wil je ontvangen ” deze basis tabel!!

nu staat er "hoeveelheid emails wil je ontvangen"  moet zijn "hoeveel e-mails wil je ontvangen"

**Comment by jorritdenbroeder** [comment]
Dat lijkt me zelfs voor een Vlaming geen correct Nederlands...
