### ISSUE TITLE
Geen (=leeg) rittenoverzicht bij VZfactuur Autopia 

### ISSUE THREAD

**Issue by MyWheels2** [MyWheels/openwheels-frontend#89]
Zie mail met voorbeeld van lege rittenstaat terwijl er wel geld gefactureerd wordt

**Comment by Aronv90** [comment]
[78.pdf](https://github.com/MyWheels/openwheels-frontend/files/16066/78.pdf)

**Comment by barthuttinga** [comment]
@Aronv90 Opgelost in release branch.
